name: New Release

on:
    workflow_dispatch:
        inputs:
            version_type:
                description: 'Semver type of new version (major / minor / patch)'
                required: true
                type: choice
                options:
                    - patch
                    - minor
                    - major
            release_type:
                description: 'Choose "preview" for experimental release'
                required: true
                type: choice
                options:
                    - release
                    - preview
jobs:
    bump-version:
        runs-on: ubuntu-latest
        steps:
            - name: Check out source
              uses: actions/checkout@v2
            - name: Setup nodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: '14.16.0'
            - run: yarn install
            - run: VERSION_TYPE=${{ github.event.inputs.version_type }} RELEASE_TYPE=${{ github.event.inputs.release_type }} node ./scripts/release.mjs
