name: New Release

on:
    workflow_dispatch:
        inputs:
            version_type:
                description: 'Semver type of new version (major / minor / patch) or prerelease (e.g. beta.0 -> beta.1)'
                required: true
                type: choice
                options:
                    - prerelease
                    - patch
                    - minor
                    - major
            release_type:
                description: 'Choose "beta" for experimental release'
                required: true
                type: choice
                options:
                    - beta
                    - release

jobs:
    bump-version:
        runs-on: ubuntu-latest
        steps:
            - name: Check out source
              uses: actions/checkout@v2
            - name: Setup nodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: '14.16.0'
            - name: setup git config
              run: |
                  git config user.name "GitHub Actions Bot"
                  git config user.email "<>"
            - run: yarn install
            - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - run: VERSION_TYPE=${{ github.event.inputs.version_type }} RELEASE_TYPE=${{ github.event.inputs.release_type }} node ./scripts/release.mjs
